---
apiVersion: v1
kind: Service
metadata:
  name: data-ingestor
  namespace: eafix-trading
  labels:
    app.kubernetes.io/name: data-ingestor
    app.kubernetes.io/component: ingestion
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: data-ingestor
---
apiVersion: v1
kind: Service
metadata:
  name: indicator-engine
  namespace: eafix-trading
  labels:
    app.kubernetes.io/name: indicator-engine
    app.kubernetes.io/component: analysis
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: indicator-engine
---
apiVersion: v1
kind: Service
metadata:
  name: signal-generator
  namespace: eafix-trading
  labels:
    app.kubernetes.io/name: signal-generator
    app.kubernetes.io/component: signals
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: signal-generator
---
apiVersion: v1
kind: Service
metadata:
  name: risk-manager
  namespace: eafix-trading
  labels:
    app.kubernetes.io/name: risk-manager
    app.kubernetes.io/component: risk
spec:
  type: ClusterIP
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: risk-manager
---
apiVersion: v1
kind: Service
metadata:
  name: execution-engine
  namespace: eafix-trading
  labels:
    app.kubernetes.io/name: execution-engine
    app.kubernetes.io/component: execution
spec:
  type: ClusterIP
  ports:
  - port: 8085
    targetPort: 8085
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: execution-engine
---
apiVersion: v1
kind: Service
metadata:
  name: calendar-ingestor
  namespace: eafix-trading
  labels:
    app.kubernetes.io/name: calendar-ingestor
    app.kubernetes.io/component: calendar
spec:
  type: ClusterIP
  ports:
  - port: 8086
    targetPort: 8086
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: calendar-ingestor
---
apiVersion: v1
kind: Service
metadata:
  name: reentry-matrix-svc
  namespace: eafix-trading
  labels:
    app.kubernetes.io/name: reentry-matrix-svc
    app.kubernetes.io/component: reentry
spec:
  type: ClusterIP
  ports:
  - port: 8087
    targetPort: 8087
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: reentry-matrix-svc
---
apiVersion: v1
kind: Service
metadata:
  name: reporter
  namespace: eafix-trading
  labels:
    app.kubernetes.io/name: reporter
    app.kubernetes.io/component: reporting
spec:
  type: ClusterIP
  ports:
  - port: 8088
    targetPort: 8088
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: reporter
---
apiVersion: v1
kind: Service
metadata:
  name: gui-gateway
  namespace: eafix-trading
  labels:
    app.kubernetes.io/name: gui-gateway
    app.kubernetes.io/component: gateway
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: gui-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: compliance-monitor
  namespace: eafix-trading
  labels:
    app.kubernetes.io/name: compliance-monitor
    app.kubernetes.io/component: compliance
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 9201
    targetPort: 9201
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: compliance-monitor