---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: eafix-ssd-retain
  labels:
    app.kubernetes.io/name: eafix-trading-system
    app.kubernetes.io/component: storage
provisioner: kubernetes.io/gce-pd  # Adjust based on cloud provider
parameters:
  type: pd-ssd
  replication-type: regional-pd
  zones: us-central1-a,us-central1-b,us-central1-c
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: eafix-ssd-retain
  gcePersistentDisk:  # Adjust based on cloud provider
    pdName: postgres-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: eafix-trading
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: eafix-ssd-retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: message-bus
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: eafix-ssd-retain
  gcePersistentDisk:  # Adjust based on cloud provider
    pdName: redis-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: eafix-trading
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: message-bus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: eafix-ssd-retain