version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: eafix-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert-rules.yml:/etc/prometheus/alert-rules.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--alertmanager.url=http://alertmanager:9093'
    depends_on:
      - alertmanager
    networks:
      - monitoring
      - eafix-network

  grafana:
    image: grafana/grafana:10.1.0
    container_name: eafix-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    networks:
      - monitoring
      - eafix-network

  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: eafix-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    networks:
      - monitoring
      - eafix-network

volumes:
  prometheus_data:
    name: eafix_prometheus_data
  grafana_data:
    name: eafix_grafana_data
  alertmanager_data:
    name: eafix_alertmanager_data

networks:
  monitoring:
    name: eafix-monitoring
  eafix-network:
    external: true