"""Derive module navigation from existing authorities; never promote evidence.

Run with --check to verify all generated bytes without writing. The graph is a
projection, not another ownership registry. Unverified execution links and
candidate contract facts remain visible as findings rather than becoming truth.
"""
from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path, PurePosixPath

import registry_core as rc

ROOT = rc.ROOT
OUTPUT = "EAFIX_auth_docs/generated/authority_graph"
POLICY = "governance/authority_graph/authority_policy.json"
ROLES = {"entrypoint", "library", "schema", "config", "fixture", "test", "doc", "data", "tooling"}


def safe_path(root, value):
    """Reject path traversal, absolute paths and escaping symlinks."""
    path = PurePosixPath(value)
    if not value or "\\" in value or ":" in value or path.is_absolute() or ".." in path.parts:
        raise ValueError(f"Unsafe repository path: {value}")
    resolved = (root / value).resolve()
    if not resolved.is_relative_to(root.resolve()):
        raise ValueError(f"Path escapes repository: {value}")
    return resolved


def role_for(path, ownership, entrypoints):
    if path in entrypoints:
        return "entrypoint"
    for key, role in (("test_files", "test"), ("schema_files", "schema"),
                      ("configuration_files", "config"), ("documentation_files", "doc")):
        if path in ownership.get(key, []):
            return "fixture" if role == "test" and "/fixtures/" in path else role
    suffix = Path(path).suffix.lower()
    if suffix in {".py", ".mq4", ".mqh"}:
        return "library"
    if suffix in {".md", ".txt", ".pdf"}:
        return "doc"
    return "data"


def validate_graph(graph):
    errors = []
    modules = {m["module_id"]: m for m in graph["modules"]}
    files = {f["path"]: f for f in graph["files"]}
    steps = {s["step_id"]: s for s in graph["steps"]}
    if len(modules) != 34 or len(modules) != len(graph["modules"]):
        errors.append("Exactly 34 unique module identities are required")
    if len(files) != len(graph["files"]):
        errors.append("File paths must be unique")
    if len(steps) != len(graph["steps"]):
        errors.append("Step IDs must be unique")
    numbers = [s["number"] for s in graph["steps"]]
    if len(set(numbers)) != len(numbers):
        errors.append("Step numbers must be unique")
    for f in graph["files"]:
        if f["role"] not in ROLES:
            errors.append(f"Invalid file role: {f['path']}")
        if f["owner_module_id"] not in modules:
            errors.append(f"Unknown owner: {f['path']}")
        if f["step_refs"] and f["role"] != "entrypoint":
            errors.append(f"Non-entrypoint has step links: {f['path']}")
        if len(f["step_refs"]) > 10:
            errors.append(f"Entrypoint exceeds 10 steps: {f['path']}")
        for sid in f["step_refs"]:
            if sid not in steps or steps[sid]["owner_module_id"] != f["owner_module_id"]:
                errors.append(f"Step/file owner mismatch: {f['path']} -> {sid}")
            elif f["path"] not in steps[sid]["entrypoint_files"]:
                errors.append(f"Missing reverse step link: {f['path']} -> {sid}")
    for s in graph["steps"]:
        m = modules.get(s["owner_module_id"])
        if not m:
            errors.append(f"Unknown step owner: {s['step_id']}")
            continue
        if not set(s["input_contract_names"]).issubset(m["input_contract_names"]):
            errors.append(f"Step inputs outside module boundary: {s['step_id']}")
        if not set(s["output_contract_names"]).issubset(m["output_contract_names"]):
            errors.append(f"Step outputs outside module boundary: {s['step_id']}")
        if len(s["entrypoint_files"]) > 5:
            errors.append(f"Step exceeds five entrypoints: {s['step_id']}")
        for path in s["entrypoint_files"]:
            f = files.get(path)
            if not f or f["role"] != "entrypoint" or f["owner_module_id"] != s["owner_module_id"]:
                errors.append(f"Invalid step entrypoint: {s['step_id']} -> {path}")
            elif s["step_id"] not in f["step_refs"]:
                errors.append(f"Missing reverse file link: {s['step_id']} -> {path}")
        for dependency in s["dependency_step_ids"]:
            if dependency not in steps:
                errors.append(f"Unknown step dependency: {dependency}")
    return errors


def build(root=ROOT):
    policy = json.loads((root / POLICY).read_text(encoding="utf-8"))
    inputs = {POLICY, "tools/registries/build_authority_graph.py",
              "governance/authority_graph/source_inventory.json",
              "EAFIX_auth_docs/01_canonical_registries/decision_registry.jsonl",
              "eafix_project_knowledge_reference_routing_instructions.json"}
    registries = {}
    for name in ("module", "process", "contract", "artifact"):
        path = f"EAFIX_auth_docs/01_canonical_registries/{name}_registry.jsonl"
        inputs.add(path)
        registries[name] = rc.read_jsonl(root / path)
    modules, manifests, findings = [], {}, []
    for record in registries["module"]:
        path = record["manifest_path"]
        manifest = json.loads(safe_path(root, path).read_text(encoding="utf-8"))
        inputs.add(path)
        identity = manifest["module_identity"]
        if identity["module_id"] != record["module_id"] or identity["canonical_symbol"] != record["canonical_symbol"]:
            raise ValueError(f"Module registry/manifest identity mismatch: {path}")
        mid = record["module_id"]
        manifests[mid] = manifest
        modules.append({"module_id": mid, "symbol": identity["canonical_symbol"],
                        "name": identity["module_name"], "root": record["module_root"],
                        "manifest_path": path, "purpose": manifest["purpose"],
                        "registry_authority_status": record["authority_status"],
                        "implementation_root": manifest["file_ownership"]["module_root"],
                        "input_contract_names": [c["name"] for c in manifest["contracts"]["input_contracts"]],
                        "output_contract_names": [c["name"] for c in manifest["contracts"]["output_contracts"]]})
    contract_by_id = {c["contract_id"]: c for c in registries["contract"]}
    file_ids = {r["relative_path"]: r["artifact_id"] for r in registries["artifact"]}
    files, owners = [], {}
    for m in modules:
        mid = m["module_id"]
        manifest = manifests[mid]
        ownership = manifest["file_ownership"]
        eps = manifest["process_binding"].get("entrypoint_files", [])
        for path in sorted(set(ownership["owned_files"])):
            if path in owners:
                raise ValueError(f"Exclusive ownership violation: {path}")
            if not safe_path(root, path).is_file():
                raise ValueError(f"Owned file missing: {path}")
            owners[path] = mid
            files.append({"path": path, "artifact_id": file_ids.get(path), "owner_module_id": mid,
                          "role": role_for(path, ownership, eps), "step_refs": [],
                          "ownership_source": m["manifest_path"]})
        for path in eps:
            if path not in ownership["owned_files"]:
                findings.append({"kind": "unverified_entrypoint", "module_id": mid, "path": path,
                                 "reason": "Declared executor is not exclusively owned; omitted from step links."})
    file_by_path = {f["path"]: f for f in files}
    steps = []
    for record in sorted(registries["process"], key=lambda r: r["step_number"]):
        mid = record["owner_module_id"]
        eps = [p for p in manifests[mid]["process_binding"].get("entrypoint_files", [])
               if p in file_by_path and file_by_path[p]["owner_module_id"] == mid]
        steps.append({"step_id": record["step_id"], "number": record["step_number"],
                      "name": record["step_name"], "owner_module_id": mid,
                      "authority_status": record["authority_status"], "trigger": record.get("trigger"),
                      "input_contract_names": [contract_by_id[c]["contract_name"] for c in record["input_contract_ids"]],
                      "output_contract_names": [contract_by_id[c]["contract_name"] for c in record["output_contract_ids"]],
                      "dependency_step_ids": record["dependency_step_ids"], "entrypoint_files": eps,
                      "validation_control_ids": record["validation_control_ids"],
                      "failure_control_ids": record["failure_control_ids"],
                      "terminal_outcomes": record.get("terminal_outcomes", [])})
        for path in eps:
            file_by_path[path]["step_refs"].append(record["step_id"])
        if not eps:
            findings.append({"kind": "missing_verified_entrypoint", "step_id": record["step_id"], "module_id": mid})
    contracts = []
    for c in registries["contract"]:
        contracts.append({"contract_id": c["contract_id"], "name": c["contract_name"], "version": c["version"],
                          "schema_ref": c["schema_ref"], "authority_status": c["authority_status"],
                          "implementation_status": c["implementation_status"],
                          "producer_module_ids": c["producer_module_ids"],
                          "consumer_module_ids": c["consumer_module_ids"],
                          "steward_module_id": policy["contract_stewards"].get(c["contract_name"]),
                          "stewardship_source": "governance/authority_graph/source_decisions.json"
                              if c["contract_name"] in policy["contract_stewards"] else None})
        if c["authority_status"] == "needs_review":
            findings.append({"kind": "unresolved_contract", "contract_id": c["contract_id"]})
    # Work cells are evidence indexed by explicit symbols or approved decisions.
    # A service directory is never treated as an ownership authority.
    decision_path = "governance/authority_graph/source_decisions.json"
    action_path = "governance/authority_graph/source_actions.json"
    inputs.update([decision_path, action_path])
    decisions = {d["source_path"]: d for d in json.loads((root / decision_path).read_text())["decisions"]}
    short_ids = {m["root"][:5]: m["module_id"] for m in modules}
    symbols = {m["symbol"]: m["module_id"] for m in modules}
    groups = defaultdict(list)
    cell_paths = set((root / "services").glob("*/work_cells/*.json"))
    cell_paths.update(root.glob("m*/m*-context/work-cells/*.json"))
    for p in sorted(cell_paths):
        rel = p.relative_to(root).as_posix()
        inputs.add(rel)
        cell = json.loads(p.read_text(encoding="utf-8"))
        decision = decisions.get(rel, {})
        mid = (short_ids.get(decision.get("approved_module_short_id"))
               or symbols.get(cell.get("parent_module_symbol"))
               or short_ids.get(rel.split("/")[0][:5]))
        groups[(cell.get("work_cell_id", p.stem), mid)].append({"path": rel,
                     "source_files": cell.get("source_files", []), "test_files": cell.get("test_files", [])})
    cells = []
    for (cid, mid), evidence in sorted(groups.items(), key=lambda pair: (pair[0][0], pair[0][1] or "")):
        candidates = {p.replace("\\", "/") for e in evidence for p in e["source_files"] + e["test_files"]}
        cells.append({"work_cell_id": cid, "related_module_id": mid,
                      "relationship_authority": "supporting_evidence", "source_refs": [e["path"] for e in evidence],
                      "verified_owned_files": sorted(p for p in candidates if owners.get(p) == mid and mid),
                      "excluded_unverified_files": sorted(p for p in candidates if not mid or owners.get(p) != mid)})
    migration = []
    for a in json.loads((root / action_path).read_text())["actions"]:
        source, target = a["source_path"], a["target_path"]
        source_exists = safe_path(root, source).is_file()
        target_exists = bool(target and safe_path(root, target).is_file())
        if source == target and source_exists:
            state = "retained_at_declared_path"
        elif target_exists and not source_exists:
            state = "target_present_source_absent"
        elif target_exists and source_exists:
            state = "both_present_requires_review"
        elif source_exists:
            state = "pending"
        else:
            state = "missing_source_and_target"
        migration.append({"source_path": source, "target_path": target, "disposition": a["approved_disposition"],
                          "filesystem_state": state, "semantic_validation": "not_asserted"})
    # Keep conflicting legacy file claims visible, never silently merge authorities.
    for a in registries["artifact"]:
        claimed = a["owner_module_id"]
        actual = owners.get(a["relative_path"])
        if claimed and actual != claimed:
            findings.append({"kind": "artifact_ownership_not_corroborated", "artifact_id": a["artifact_id"],
                             "path": a["relative_path"], "registry_owner": claimed, "manifest_owner": actual})
    graph = {"schema_version": "1.0.0", "document_type": "generated_authority_navigation",
             "source_policy": POLICY, "authority_status": "generated", "modules": modules,
             "steps": steps, "files": files, "contracts": contracts, "work_cells": cells,
             "findings": findings, "migration_observations": migration}
    edges = []
    for f in files:
        edges.append({"from": f["owner_module_id"], "to": f["path"], "type": "owns_file"})
        for sid in f["step_refs"]:
            edges.append({"from": f["path"], "to": sid, "type": "declared_executor"})
    for s in steps:
        edges.append({"from": s["owner_module_id"], "to": s["step_id"], "type": "owns_step"})
        for dependency in s["dependency_step_ids"]:
            edges.append({"from": dependency, "to": s["step_id"], "type": "step_precedes"})
    for c in contracts:
        for mid in c["producer_module_ids"]:
            edges.append({"from": mid, "to": c["contract_id"], "type": "registry_declared_producer",
                          "authority_status": c["authority_status"]})
        for mid in c["consumer_module_ids"]:
            edges.append({"from": c["contract_id"], "to": mid, "type": "registry_declared_consumer",
                          "authority_status": c["authority_status"]})
        if c["steward_module_id"]:
            edges.append({"from": c["steward_module_id"], "to": c["contract_id"], "type": "contract_steward"})
    graph["edges"] = sorted(edges, key=lambda e: (e["type"], e["from"], e["to"]))
    errors = validate_graph(graph)
    if errors:
        raise ValueError("\n".join(errors))
    hashes = {path: rc.normalized_file_sha(safe_path(root, path)) for path in sorted(inputs)}
    graph["source_hashes"] = hashes
    outputs = {f"{OUTPUT}/authority_graph.current.json": graph}
    for m in modules:
        mid = m["module_id"]
        module_steps = [s for s in steps if s["owner_module_id"] == mid]
        packet = {"schema_version": "1.0.0", "packet_type": "generated_module_navigation",
                  "authority_status": "generated", "module": m, "steps": module_steps,
                  "files": [f for f in files if f["owner_module_id"] == mid],
                  "contracts": [c for c in contracts if mid in c["producer_module_ids"] + c["consumer_module_ids"]],
                  "work_cells": [c for c in cells if c["related_module_id"] == mid],
                  "findings": [f for f in findings if f.get("module_id") == mid], "source_hashes": hashes}
        outputs[f"{OUTPUT}/modules/{mid}.json"] = packet
        diagrams = []
        diagram_steps = module_steps or [{"trigger": "Trigger not yet specified in canonical process",
                  "input_contract_names": m["input_contract_names"],
                  "output_contract_names": m["output_contract_names"],
                  "failure_control_ids": ["Failure policy not yet specified in canonical process"]}]
        for step in diagram_steps:
            consumers = sorted({other["symbol"] for other in modules if other["module_id"] != mid
                          and set(step["output_contract_names"]) & set(other["input_contract_names"])})
            diagrams.append("\n".join(["flowchart TD",
                f'  trigger["Trigger: {escape(step["trigger"] or "unspecified")}"]',
                f'  input["Input: {escape(", ".join(step["input_contract_names"]))}"]',
                f'  boundary["{escape(m["symbol"])}"]',
                '  decision{"Boundary validation"}',
                f'  output["Output: {escape(", ".join(step["output_contract_names"]))}"]',
                f'  failure["Failure controls: {escape(", ".join(step["failure_control_ids"]))}"]',
                '  trigger --> boundary', '  input --> boundary', '  boundary --> decision',
                '  decision -->|valid| output', '  decision -->|invalid| failure',
                f'  next["Declared consumers: {escape(", ".join(consumers) or "none declared")}"]',
                '  output --> next']))
        outputs[f"{OUTPUT}/diagrams/{mid}.md"] = (f"# {m['symbol']}\n\nGenerated boundary view; execution is not certified.\n\n" +
             ("\n\n".join("```mermaid\n" + d + "\n```" for d in diagrams) if diagrams else
              "No canonical process step is assigned. Inputs and outputs remain declared in the module manifest.\n"))
    counts = defaultdict(int)
    for finding in findings:
        counts[finding["kind"]] += 1
    outputs[f"{OUTPUT}/validation_report.json"] = {"navigation_validation": "pass", "errors": [],
          "module_count": len(modules), "step_count": len(steps), "owned_file_count": len(files),
          "contract_count": len(contracts), "work_cell_group_count": len(cells),
          "migration_action_count": len(migration), "finding_counts": dict(counts),
          "production_ready": False, "authority_cutover_performed": False,
          "reason": "Candidate authorities, ownership coverage and runtime execution remain unresolved."}
    outputs[f"{OUTPUT}/README.md"] = navigation_readme(graph)
    return outputs


def escape(text):
    return text.replace('"', "'").replace("\n", " ").replace("<", "(").replace(">", ")")


def navigation_readme(graph):
    lines = ["# EAFIX generated module navigation", "",
             "Generated from existing manifests and registries. This directory is a projection and must not be edited manually.", "",
             "Regenerate: `python tools/registries/build_authority_graph.py`.",
             "Verify without writing: `python tools/registries/build_authority_graph.py --check`.", "",
             "Shared contract stewardship, producer roles and consumption are separate from physical file ownership.",
             "Candidate records retain their status. Missing executable links and unresolved contracts appear in the validation report.", "",
             "| Module | Steps | Owned files | Navigation | Boundary view |",
             "|---|---|---:|---|---|"]
    for m in graph["modules"]:
        mid = m["module_id"]
        steps = ", ".join(str(s["number"]) for s in graph["steps"] if s["owner_module_id"] == mid) or "none"
        count = sum(f["owner_module_id"] == mid for f in graph["files"])
        lines.append(f"| {m['symbol']} | {steps} | {count} | [JSON](modules/{mid}.json) | [Diagram](diagrams/{mid}.md) |")
    return "\n".join(lines) + "\n"


def run(check=False, root=ROOT):
    outputs = build(root)
    expected = {path: value if isinstance(value, str) else json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
                for path, value in outputs.items()}
    changed = []
    for path, text in expected.items():
        destination = safe_path(root, path)
        if not destination.exists() or destination.read_text(encoding="utf-8") != text:
            changed.append(path)
        if not check:
            rc.write_text(destination, text)
    # A removed module must not leave behind stale navigational claims.
    extras = [p.relative_to(root).as_posix() for p in (root / OUTPUT).rglob("*")
              if p.is_file() and p.relative_to(root).as_posix() not in expected]
    if extras:
        raise ValueError(f"Unexpected generated files require review: {extras}")
    print(f"authority navigation: {len(outputs)} outputs; differences={len(changed)}")
    return 1 if check and changed else 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        raise SystemExit(run(args.check))
    except (ValueError, KeyError, OSError) as exc:
        parser.exit(1, f"Authority graph validation failed: {exc}\n")
