name: contracts-compat
on:
  pull_request:
    paths:
      - 'contracts/**'
  push:
    branches: [ main ]
    paths:
      - 'contracts/**'
jobs:
  compat-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: python -m pip install jsonschema
      - name: Check schema compatibility
        env:
          BASE_REF: origin/main
        run: python ci/check_schema_compat.py
